name: Test Apache archive download

on:
  workflow_dispatch:

env:
  proton: 0.40.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: cache
      uses: actions/cache@v4
      with:
        path: proton
        key: proton-${{ env.proton }}
        enableCrossOsArchive: true
    - if: steps.cache.outputs.cache-hit != 'true'
      working-directory: proton
      run: |
        curl -fLOsS https://archive.apache.org/dist/qpid/proton/${proton}/qpid-proton-${proton}.tar.gz.asc
        curl -fLOsS https://archive.apache.org/dist/qpid/proton/${proton}/qpid-proton-${proton}.tar.gz
    - working-directory: proton
      run: |
        curl -fLOsS https://downloads.apache.org/qpid/KEYS
        gpg --no-default-keyring --keyring trustedkeys.kbx --import KEYS
    - working-directory: proton
      run: |
        gpgv qpid-proton-${proton}.tar.gz.asc qpid-proton-${proton}.tar.gz
