# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.created.outputs.created }}
    steps:
    - id: created
      run: echo "::set-output name=created::$(date --utc +%Y-%m-%dT%H:%M:%SZ)"


  # This workflow contains a single job called "build"
  production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: pre
    strategy:
      matrix:
        include:
          - image: a
          - image: b
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # https://docs.docker.com/build/ci/github-actions/cache/
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx
          key: buildx-${{ matrix.image }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ matrix.image }}-

      # https://github.com/docker/compose/pull/9466
      # - name: Build docker-compose
      #   run: docker compose build

      - name: Build
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ${{ matrix.context || matrix.image }}
          file: ${{ matrix.dockerfile || format('{0}/{1}', matrix.context || matrix.image, 'Dockerfile') }}
          build-args: |
            CREATED=${{ needs.pre.outputs.created }}
            SOURCE_COMMIT=${{ github.sha }}
          # labels: |
          load: true
          # Maybe push straight to the Azure registry? push: true
          tags: |
            okoko/${{ matrix.image }}:${{ github.run_number }}
          # https://docs.docker.com/build/ci/github-actions/cache/
          cache-from: type=local,src=/tmp/.buildx
          cache-to: type=local,dest=/tmp/.buildx-new,mode=max

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx
          mv /tmp/.buildx-new /tmp/.buildx

  post:
    runs-on: ubuntu-latest
    needs: production
    steps:
      - name: Done
        run: "true"
