on:
  push:
    branches:
      - main

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - run: git config -l
      - run: cat ~/.gitconfig
        continue-on-error: true
      - uses: actions/checkout@v3
      - run: cat .git/config
      - run: cat ~/.gitconfig
        continue-on-error: true
      - run: git config -l
