name: Test script

on:
  push:

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/github-script@v6
        id: previous
        with:
          script: |
            // https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#push
            // https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts
            console.log('context:', context)

            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'github-script.yml',
              branch: 'main',
              event: 'push',
              status: 'success',
              per_page: 1,
            });
            core.setOutput('sha', runs.data.workflow_runs[0].head_sha)

            console.log('runs:', runs)
            for(const run of runs.data.workflow_runs) {
              console.log(run)
            }

      - run: echo ${{ steps.previous.outputs.sha }}
