name: Test script

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#push
            // https://github.com/actions/toolkit/blob/main/packages/github/src/context.ts
            console.log('event:', context.payload)
            context.payload.repo.
            const runs = github.rest.actions.listWorkflowRuns({
              owner: context.payload.repo.owner,
              repo: context.payload.repo.repo,
              workflow_id: 'github-script.yml',
              branch: 'main',
              event: 'push',
              status: 'success',
            });
            console.log('runs:', runs)
