name: Test pwsh

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Print FormatEnumerationLimit
      run: |
        $FormatEnumerationLimit
    - name: Print version
      run: |
        $FormatEnumerationLimit = 256
        $PSVersionTable
    - name: Print FormatEnumerationLimit
      run: |
        $FormatEnumerationLimit
    - name: List variables
      continue-on-error: true
      run: |
        $FormatEnumerationLimit = 256
        Get-Variable -Exclude FormatEnumerationLimit | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: List environment variables
      run: |
        Get-ChildItem Env: | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: List modules imported
      run: |
        Get-Module | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: List modules available
      run: |
        Get-Module -ListAvailable | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: List commands
      run: |
        Get-Command * | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: List drives
      continue-on-error: true
      run: |
        Get-PSDrive | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: List providers
      continue-on-error: true
      run: |
        Get-PSProvider | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: List sessions
      continue-on-error: true
      run: |
        Get-PSSession | Format-Table -AutoSize -Wrap | Out-String -Width 256
    - name: Find module files
      shell: bash
      run: |
        find / -xdev -name '*.psm1'
