name: Python

on:
  workflow_dispatch:

defaults:
  run:
    shell: python

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Print Python version
      run: |
        import sys
        print(sys.executable, sys.version)

    - name: List installed packages
      run: |
        from importlib.metadata import Distribution
        for d in Distribution.discover():
            print(f"{d.name}=={d.version}")

    - name: Install Jinja2
      shell: bash
      run: |
        python -m pip install cube-solver

    - name: List installed packages
      continue-on-error: true
      run: |
        from importlib.metadata import version
        print(f"cube-solver=={version('cube-solver')}")

    - name: Test Jinja2 installation
      run: |
        from jinja2 import Template
        template = Template("Hello, {{ name }}!")
        output = template.render(name="World")
        print(output)
