name: Check runner

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: test-env
    steps:
    # https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#versions
    - name: Get IMDS versions
      continue-on-error: true
      run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/versions" | jq
    # The latest version was last in the array.

    # (Seems the filtering is not supported)
    - name: Check if getting the oldest version is supported
      continue-on-error: true
      run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/versions/apiVersions/0?format=text"

    - name: Check if getting the newest version is supported
      continue-on-error: true
      run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/versions/apiVersions/-1?format=text"

    - name: Get runner VM metadata
      continue-on-error: true
      run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2023-07-01" | jq

    - name: Get only the region
      continue-on-error: true
      # leaf nodes require the format=text query parameter
      run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/location?api-version=2023-07-01&format=text"

    # requests to IMDS are limited to 5 requests per second
    - name: Sleep for rate limit
      run: sleep 1

    - name: Check the attestation
      continue-on-error: true
      # leaf nodes require the format=text query parameter
      run: |
        # Get the signature
        curl --silent -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/attested/document?api-version=2020-09-01" | jq -r '.["signature"]' > signature
        cat signature
        # Decode the signature
        base64 -d signature > decodedsignature
        # Get PKCS7 format
        openssl pkcs7 -in decodedsignature -inform DER -out sign.pk7
        # Get Public key out of pkc7
        openssl pkcs7 -in decodedsignature -inform DER  -print_certs -out signer.pem
        # Get the intermediate certificate
        curl -s -o intermediate.cer "$(openssl x509 -in signer.pem -text -noout | grep " CA Issuers -" | awk -FURI: '{print $2}')"
        openssl x509 -inform der -in intermediate.cer -out intermediate.pem
        # Verify the contents
        openssl smime -verify -in sign.pk7 -inform pem -noverify

    # https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http
    - name: Get access token
      continue-on-error: true
      run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/" | jq

    # This takes some time because events are not enabled by default
    # https://learn.microsoft.com/en-us/azure/virtual-machines/linux/scheduled-events#enabling-and-disabling-scheduled-events
    # - name: Get events
    #   continue-on-error: true
    #   run: curl -s -H Metadata:true "http://169.254.169.254/metadata/scheduledevents?api-version=2020-07-01" | jq

    - name: id
      run: id

    - name: scan pipx
      run: pipx list

    - name: List environment
      run: env | sort

    - name: List /opt files
      continue-on-error: true
      run: find /opt -maxdepth 3 -ls

    - name: List /usr/local files
      continue-on-error: true
      run: find /usr/local -maxdepth 3 -ls

    - name: List home files
      continue-on-error: true
      run: find /home/runner -maxdepth 3 -ls

    - name: Find commands
      run: |
        IFS=:
        for d in $PATH
        do
          echo --- "$d"
          ls -l "$d" || :
        done

    - name: Find apt sources
      run: |
        cat /etc/apt/sources.list
        grep . /etc/apt/sources.list.d/*
        dpkg -l

    - name: List /etc files
      continue-on-error: true
      run: find /etc -ls

    - name: docker system info
      run: |
        docker system info
        [ -r /etc/docker/daemon.json ] && cat /etc/docker/daemon.json

    - name: Show runner context
      run: echo '${{ toJSON(runner) }}'
    - name: Show env context
      run: echo '${{ toJSON(env) }}'
    - name: Show secrets context
      run: echo "$SECRETS"
      env:
        SECRETS: ${{ toJSON(secrets) }}
