name: Check runner

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: test-env
    steps:
    - name: id
      run: id
      
    - name: scan pipx
      run: pipx list
      
    - name: List environment
      run: env | sort

    - name: List /opt files
      run: find /opt -maxdepth 3 -ls
      
    - name: List /usr/local files
      run: find /usr/local -maxdepth 3 -ls

    - name: List home files
      run: find /home/runner -maxdepth 3 -ls
      
    - name: Find commands
      run: |
        IFS=:
        for d in $PATH
        do
          echo --- "$d"
          ls -l "$d" || :
        done

    - name: Find apt sources
      run: |
        cat /etc/apt/sources.list
        grep . /etc/apt/sources.list.d/*
        dpkg -l

    - name: docker system info
      run: |
        docker system info
        cat /etc/docker/daemon.json

    - name: Show runner context
      run: echo '${{ toJSON(runner) }}'
    - name: Show env context
      run: echo '${{ toJSON(env) }}'
    - name: Show secrets context
      run: echo "$SECRETS"
      env:
        SECRETS: ${{ toJSON(secrets) }}
