name: Test add-mask

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '    "msg": "::add-mask::salaisuus"'
    - run: |
        echo '    ::add-mask::salattu'
    - run: |
        echo '::add-mask::rivinalussa'
    - run: |
        echo 'salaisuus  salaisuus" salattu  rivinalussa'
        
    - run: |
        echo "FOO=bar" >> "$GITHUB_ENV"
    - run: |
        env
        echo "${{ toJSON(env) }}"
      env:
        BAZ: ${{ env.FOO }}
